

no-permissions-for-command: "You don't have enough permissions to run this command."
no-permissions-for-warp: "You don't have enough permissions to run this command."
no-warp-for-name: "This name doesn't correspond to any warp."
